version: '3'
services:
  db: 
    image: bjarkt/opn_take_home:db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: people
    ports:
      - "3306:3306"
  
  backend:
    image: bjarkt/opn_take_home:backend
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db

  www:
    image: bjarkt/opn_take_home:www
    ports:
      - "443:443"
    depends_on:
      - backend

