version: '3'
services:
  db: 
    image: bjarkt/take_home_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: people
    ports:
      - "3306:3306"
  
  backend:
    image: bjarkt/take_home_backend
    environment:
      PORT: 3000
    ports:
      - "3000:3000"

  www:
    image: bjarkt/take_home_www
    ports:
      - "80:80"